server:
  port: ${port}


spring:
  application:
    name: yjy-project
  profiles:
    active: @env@
  datasource:
    driver-class-name: ${db.driver}
    #schema: classpath:db/schema-h2.sql
    #data: classpath:db/data-h2.sql
    username: ${db.username}
    password: ${db.password}
    url: ${db.url}?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&serverTimezone=UTC
mybatis-plus:
  configuration:
    cache-enabled: false
  redis:
    # host: 127.0.0.1
    #    host: 106.54.22.115
    #    port: 6379
    #  timeout: 30
    redisson:
      config: classpath:redisson.yml

dingding:
  #开放平台首页 公司id
  appType: ${dingding.appType}
  corpId: ${dingding.corpId}
  appKey: ${dingding.appKey}
  appSecret: ${dingding.appSecret}


swagger:
  enable: ${swagger.enable}
  basePackage: ${swagger.basePackage}

redis:
  cache:
    time:
      #账号信息缓存时长 单位天
      account: 30
      #token缓存时间 单位天
      token: 30


# AES密码加密私钥(Base64加密)
encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==
# JWT认证加密私钥(Base64加密)
encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
  # AccessToken过期时间单位天
accessTokenExpireTime: 30
